In [10]:
import tensorflow as tf
import numpy as np
import h5py as h5
import os
import re
import pandas as pd

In [ ]:
# def load_h5_pdf(h5file,groupname,fields=None,index=None):
#     "Reads several fields from an HDF5 file and turns the results into a pandas dataframe" 
#     if fields is None:
#         fields=get_h5_dnames(h5file,groupname)
#     tpdf =pd.DataFrame(dict(zip(fields,[load_h5_dname(h5file,groupname,field,index) for field in fields])))
#     #tpdf['index_id']=pd.Series(range(len(tpdf)),index=tpdf.index)
#     return tpdf


In [2]:

Ne = tf.constant([10000],name='Ne')
a = tf.constant([1,2,3],name='a')
b= tf.constant([1,2,3],name='b')
dist_op = tf.abs(tf.expand_dims(a,1)-b)


In [4]:
shrinkmat = 4*Ne*dist_op/100

with tf.Session() as session:
    print(session.run(shrinkmat))

[[   0.  400.  800.]
 [ 400.    0.  400.]
 [ 800.  400.    0.]]


In [ ]:
import edward as ed
import numpy as np
import tensorflow as tf

from edward.models import Normal

In [3]:
dataset1 = tf.contrib.data.Dataset.from_tensor_slices(tf.random_uniform([4, 10]))
print(dataset1.output_types)  # ==> "tf.float32"
print(dataset1.output_shapes)  # ==> "(10,)"

<dtype: 'float32'>
(10,)


In [8]:
h5file = '/home/nwknoblauch/Desktop/scratch/polyg_scratch/hdf5/sub_seq_hapmap.h5'
hf = h5.File(h5file,mode='r')
hf

<HDF5 file "sub_seq_hapmap.h5" (mode r)>

array([[ 1.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])